"""Full six-language vocab. Book pages first, then extra related words."""

from __future__ import annotations


def t(en: str, es: str, pt: str, it: str, fr: str, ko: str) -> dict[str, str]:
    return {"en": en, "es": es, "pt": pt, "it": it, "fr": fr, "ko": ko}


VOCAB: dict[str, list[dict[str, str]]] = {
    "restaurant": [
        t("the bill / check", "la cuenta", "a conta", "il conto", "l'addition", "계산서"),
        t("lamb", "el cordero", "o cordeiro", "l'agnello", "l'agneau", "양고기"),
        t("plate", "el plato", "o prato", "il piatto", "l'assiette", "접시"),
        t("cashier (f.)", "la cajera", "a caixa", "la cassiera", "la caissière", "계산원"),
        t("chops", "las chuletas", "as costeletas", "le cotolette", "les cotelettes", "커틀릿"),
        t("knife", "el cuchillo", "a faca", "il coltello", "le couteau", "나이프"),
        t("shrimp", "los camarones", "os camarões", "i gamberi", "les crevettes", "새우"),
        t("lunch", "el almuerzo", "o almoço", "il pranzo", "le déjeuner", "점심"),
        t("custard", "el flan", "o pudim", "il budino", "le flan", "플랑"),
        t("fork", "el tenedor", "o garfo", "la forchetta", "la fourchette", "포크"),
        t("fries", "las patatas fritas", "as batatas fritas", "le patatine fritte", "les frites", "감자튀김"),
        t("seafood", "los mariscos", "os frutos do mar", "i frutti di mare", "les fruits de mer", "해산물"),
        t("waiter", "el camarero", "o garçom", "il cameriere", "le garçon", "웨이터"),
        t("to buy", "comprar", "comprar", "comprare", "acheter", "사다"),
        t("to have", "tener", "ter", "avere", "avoir", "가지다"),
        t("to drink", "beber", "beber", "bere", "boire", "마시다"),
        t("to look for", "buscar", "procurar", "cercare", "chercher", "찾다"),
        t("to order", "pedir / ordenar", "pedir", "ordinare", "commander", "주문하다"),
        t("to start", "empezar", "começar", "cominciare", "commencer", "시작하다"),
        t("to ask", "pedir / preguntar", "pedir / perguntar", "chiedere", "demander", "묻다"),
        t("to hear", "oír", "ouvir", "sentire", "entendre", "듣다"),
        t("to be", "ser / estar", "ser / estar", "essere", "être", "이다"),
        t("to eat", "comer", "comer", "mangiare", "manger", "먹다"),
        t("afternoon", "la tarde", "a tarde", "il pomeriggio", "l'après-midi", "오후"),
        t("with", "con", "com", "con", "avec", "함께"),
        t("ice cream", "el helado", "o sorvete", "il gelato", "la glace", "아이스크림"),
        t("lobster", "la langosta", "a lagosta", "l'astice", "le homard", "랍스터"),
        t("garden", "el jardín", "o jardim", "il giardino", "le jardin", "정원"),
        t("lettuce", "la lechuga", "a alface", "la lattuga", "la laitue", "상추"),
        t("crayfish", "el bogavante / cigala", "a lagosta", "l'aragosta", "la langouste", "가재"),
        t("vegetables", "las verduras", "os legumes", "le verdure", "les légumes", "채소"),
        t("dish", "el plato", "o prato", "il piatto", "le plat", "요리"),
        t("fish", "el pescado", "o peixe", "il pesce", "le poisson", "생선"),
        t("chicken", "el pollo", "o frango", "il pollo", "le poulet", "닭고기"),
        t("meal", "la comida", "a refeição", "il pasto", "le repas", "식사"),
        t("napkin", "la servilleta", "o guardanapo", "il tovagliolo", "la serviette", "냅킨"),
        t("veal", "la ternera", "a vitela", "il vitello", "le veau", "송아지 고기"),
        t("glass", "el vaso", "o copo", "il bicchiere", "le verre", "잔"),
        t("meat", "la carne", "a carne", "la carne", "la viande", "고기"),
        t("to leave", "irse / salir", "partir / sair", "partire", "partir", "떠나다"),
        t("to prefer", "preferir", "preferir", "preferire", "préférer", "선호하다"),
        t("to take", "tomar / coger", "pegar / tomar", "prendere", "prendre", "가져가다"),
        t("to come back", "volver", "voltar", "tornare", "revenir", "돌아오다"),
        t("to know", "saber", "saber", "sapere", "savoir", "알다"),
        t("to work", "trabajar", "trabalhar", "lavorare", "travailler", "일하다"),
        t("to find", "encontrar", "encontrar", "trovare", "trouver", "찾다"),
        t("to sell", "vender", "vender", "vendere", "vendre", "팔다"),
        t("to want", "querer", "querer", "volere", "vouloir", "원하다"),
        t("me too", "yo también", "eu também", "anch'io", "moi aussi", "나도"),
        t("because", "porque", "porque", "perché", "parce que", "왜냐하면"),
        t("maybe", "quizá / tal vez", "talvez", "forse", "peut-être", "아마"),
        t("sometimes", "a veces", "às vezes", "qualche volta", "quelquefois", "가끔"),
        t("often", "a menudo", "muitas vezes", "spesso", "souvent", "자주"),
        t("superb", "soberbio", "soberbo", "superbo", "superbe", "훌륭한"),
        t("truly", "de verdad", "realmente", "davvero", "vraiment", "정말로"),
        t("menu", "la carta", "o cardápio", "il menù", "le menu", "메뉴"),
        t("wine", "el vino", "o vinho", "il vino", "le vin", "와인"),
        t("water", "el agua", "a água", "l'acqua", "l'eau", "물"),
        t("dessert", "el postre", "a sobremesa", "il dolce", "le dessert", "디저트"),
        t("tip", "la propina", "a gorjeta", "la mancia", "le pourboire", "팁"),
        t("vegetarian", "vegetariano", "vegetariano", "vegetariano", "végétarien", "채식"),
        t("delicious", "delicioso", "delicioso", "delizioso", "délicieux", "맛있는"),
        t("appetizer", "el entrante", "a entrada", "l'antipasto", "l'entrée", "전채"),
        t("salt", "la sal", "o sal", "il sale", "le sel", "소금"),
        t("pepper", "la pimienta", "a pimenta", "il pepe", "le poivre", "후추"),
        t("bread", "el pan", "o pão", "il pane", "le pain", "빵"),
        t("table", "la mesa", "a mesa", "il tavolo", "la table", "테이블"),
        t("hungry", "hambriento", "faminto", "affamato", "affamé", "배고픈"),
        t("thirsty", "sediento", "com sede", "assetato", "assoiffé", "목마른"),
        t("the check please", "la cuenta, por favor", "a conta, por favor", "il conto, per favore", "l'addition, s'il vous plaît", "계산서 주세요"),
    ],
    "store": [
        t("purchase", "la compra", "a compra", "l'acquisto", "l'achat", "구매"),
        t("money", "el dinero", "o dinheiro", "i soldi", "l'argent", "돈"),
        t("box", "la caja / la caja", "a caixa", "la scatola", "la boîte", "상자"),
        t("truck", "el camión", "o caminhão", "il camion", "le camion", "트럭"),
        t("cashier's desk", "la caja", "o caixa", "la cassa", "la caisse", "계산대"),
        t("ashtray", "el cenicero", "o cinzeiro", "il posacenere", "le cendrier", "재떨이"),
        t("room", "la habitación", "o quarto", "la stanza", "la chambre", "방"),
        t("thing", "la cosa", "a coisa", "la cosa", "la chose", "것"),
        t("armchair", "el sillón", "a poltrona", "la poltrona", "le fauteuil", "안락의자"),
        t("bed", "la cama", "a cama", "il letto", "le lit", "침대"),
        t("furniture", "los muebles", "os móveis", "i mobili", "les meubles", "가구"),
        t("price / cost", "el precio", "o preço", "il prezzo", "le prix", "가격"),
        t("aisle / department", "el pasillo / sección", "o corredor / seção", "il corridoio / reparto", "le rayon", "매대"),
        t("dress", "el vestido", "o vestido", "il vestito", "la robe", "원피스"),
        t("value", "el valor", "o valor", "il valore", "la valeur", "가치"),
        t("salesman", "el vendedor", "o vendedor", "il commesso", "le vendeur", "점원"),
        t("saleswoman", "la vendedora", "a vendedora", "la commessa", "la vendeuse", "여점원"),
        t("neighborhood", "el vecindario", "o bairro", "il vicinato", "le voisinage", "동네"),
        t("will (n.)", "la voluntad", "a vontade", "la volontà", "la volonté", "의지"),
        t("to accompany", "acompañar", "acompanhar", "accompagnare", "accompagner", "동행하다"),
        t("to admire", "admirar", "admirar", "ammirare", "admirer", "감탄하다"),
        t("to help", "ayudar", "ajudar", "aiutare", "aider", "돕다"),
        t("to bring", "traer", "trazer", "portare", "apporter", "가져오다"),
        t("to putter around", "trastear", "fazer bicos", "smanettare", "bricoler", "손보다"),
        t("to count", "contar", "contar", "contare", "compter", "세다"),
        t("to cost", "costar", "custar", "costare", "coûter", "비용이 들다"),
        t("to get off / go down", "bajar", "descer", "scendere", "descendre", "내리다"),
        t("to wish / desire", "desear", "desejar", "desiderare", "désirer", "바라다"),
        t("to discuss", "discutir", "discutir", "discutere", "discuter", "논의하다"),
        t("to last", "durar", "durar", "durare", "durer", "지속하다"),
        t("to hope", "esperar", "esperar", "sperare", "espérer", "희망하다"),
        t("it is", "es", "é", "è", "c'est", "이다"),
        t("already", "ya", "já", "già", "déjà", "이미"),
        t("since", "desde", "desde", "da", "depuis", "부터"),
        t("to celebrate", "festejar", "comemorar", "festeggiare", "fêter", "축하하다"),
        t("to waste", "desperdiciar", "desperdiçar", "sprecare", "gaspiller", "낭비하다"),
        t("to hesitate", "dudar / vacilar", "hesitar", "esitare", "hésiter", "망설이다"),
        t("to walk / to work (machine)", "andar / funcionar", "andar / funcionar", "camminare / funzionare", "marcher", "걷다 / 작동하다"),
        t("to show", "mostrar", "mostrar", "mostrare", "montrer", "보여주다"),
        t("to carry / wear", "llevar", "carregar / usar", "portare", "porter", "나르다"),
        t("to bring back", "traer de vuelta", "trazer de volta", "riportare", "ramener", "되가져오다"),
        t("to return home", "volver a casa", "voltar para casa", "rincasare", "rentrer", "귀가하다"),
        t("to follow", "seguir", "seguir", "seguire", "suivre", "따르다"),
        t("with pleasure", "con mucho gusto", "com prazer", "con piacere", "avec plaisir", "기꺼이"),
        t("darn!", "¡vaya!", "poxa!", "accidenti!", "zut !", "에이!"),
        t("shirt", "la camisa", "a camisa", "la camicia", "la chemise", "셔츠"),
        t("to receive", "recibir", "receber", "ricevere", "recevoir", "받다"),
        t("receipt", "el recibo", "o recibo", "lo scontrino", "le reçu", "영수증"),
        t("credit card", "la tarjeta de crédito", "o cartão de crédito", "la carta di credito", "la carte de crédit", "신용카드"),
        t("cheap", "barato", "barato", "economico", "bon marché", "싼"),
        t("expensive", "caro", "caro", "caro", "cher", "비싼"),
        t("sale / bargain", "las rebajas", "a promoção", "i saldi", "les soldes", "세일"),
        t("bag", "la bolsa", "a sacola", "la borsa", "le sac", "가방"),
        t("to pay", "pagar", "pagar", "pagare", "payer", "지불하다"),
        t("open", "abierto", "aberto", "aperto", "ouvert", "열린"),
        t("closed", "cerrado", "fechado", "chiuso", "fermé", "닫힌"),
        t("how much?", "¿cuánto cuesta?", "quanto custa?", "quanto costa?", "ça coûte combien ?", "얼마예요?"),
        t("too expensive", "demasiado caro", "caro demais", "troppo caro", "trop cher", "너무 비싸다"),
        t("I'll take it", "me lo llevo", "vou levar", "lo prendo", "je le prends", "이걸로 할게요"),
        t("gift wrap", "envolver para regalo", "embalar para presente", "confezionare", "emballer en cadeau", "선물 포장"),
        t("escalator", "la escalera mecánica", "a escada rolante", "la scala mobile", "l'escalier mécanique", "에스컬레이터"),
        t("fitting room", "el probador", "o provador", "il camerino", "la cabine d'essayage", "탈의실"),
    ],
    "airport": [
        t("airport", "el aeropuerto", "o aeroporto", "l'aeroporto", "l'aéroport", "공항"),
        t("round-trip", "ida y vuelta", "ida e volta", "andata e ritorno", "aller-retour", "왕복"),
        t("to announce", "anunciar", "anunciar", "annunciare", "annoncer", "안내하다"),
        t("arrival", "la llegada", "a chegada", "l'arrivo", "l'arrivée", "도착"),
        t("landing", "el aterrizaje", "o pouso", "l'atterraggio", "l'atterrissage", "착륙"),
        t("airplane", "el avión", "o avião", "l'aereo", "l'avion", "비행기"),
        t("baggage", "el equipaje", "a bagagem", "i bagagli", "les bagages", "수하물"),
        t("ticket", "el billete", "a passagem", "il biglietto", "le billet", "표"),
        t("boarding pass", "la tarjeta de embarque", "o cartão de embarque", "la carta d'imbarco", "la carte d'embarquement", "탑승권"),
        t("seat belt", "el cinturón", "o cinto", "la cintura", "la ceinture", "안전벨트"),
        t("choice", "la elección", "a escolha", "la scelta", "le choix", "선택"),
        t("controls", "los mandos", "os comandos", "i comandi", "les commandes", "조종장치"),
        t("departure", "la salida", "a partida", "la partenza", "le départ", "출발"),
        t("to help", "ayudar", "ajudar", "aiutare", "aider", "돕다"),
        t("to light / turn on", "encender", "acender", "accendere", "allumer", "켜다"),
        t("to stop", "parar", "parar", "fermare", "arrêter", "멈추다"),
        t("to arrive / happen", "llegar / ocurrir", "chegar / acontecer", "arrivare / succedere", "arriver", "도착하다"),
        t("to fasten", "abrochar", "afivelar", "allacciare", "attacher", "매다"),
        t("to land", "aterrizar", "pousar", "atterrare", "atterrir", "착륙하다"),
        t("to take off", "despegar", "decolar", "decollare", "décoller", "이륙하다"),
        t("to go down", "bajar", "descer", "scendere", "descendre", "내려가다"),
        t("to unfasten", "desabrochar", "desafivelar", "slacciare", "détacher", "풀다"),
        t("to have to", "deber", "dever", "dovere", "devoir", "해야 하다"),
        t("to board", "embarcar", "embarcar", "imbarcarsi", "embarquer", "탑승하다"),
        t("customs", "la aduana", "a alfândega", "la dogana", "la douane", "세관"),
        t("customs officer", "el aduanero", "o agente da alfândega", "il doganiere", "le douanier", "세관원"),
        t("window", "la ventana", "a janela", "il finestrino", "la fenêtre", "창"),
        t("loudspeaker", "el altavoz", "o alto-falante", "l'altoparlante", "le haut-parleur", "스피커"),
        t("flight attendant", "la azafata", "a aeromoça", "l'hostess", "l'hôtesse", "승무원"),
        t("light", "la luz", "a luz", "la luce", "la lumière", "빛"),
        t("passenger", "el pasajero", "o passageiro", "il passeggero", "le passager", "승객"),
        t("pilot", "el piloto", "o piloto", "il pilota", "le pilote", "조종사"),
        t("runway", "la pista", "a pista", "la pista", "la piste de décollage", "활주로"),
        t("door / gate", "la puerta", "a porta / o portão", "la porta / il gate", "la porte", "문 / 게이트"),
        t("seat", "el asiento", "o assento", "il sedile", "le siège", "좌석"),
        t("exit", "la salida", "a saída", "l'uscita", "la sortie", "출구"),
        t("vacation", "las vacaciones", "as férias", "le vacanze", "les vacances", "휴가"),
        t("suitcase", "la maleta", "a mala", "la valigia", "la valise", "여행 가방"),
        t("flight", "el vuelo", "o voo", "il volo", "le vol", "항공편"),
        t("trip", "el viaje", "a viagem", "il viaggio", "le voyage", "여행"),
        t("traveler", "el viajero", "o viajante", "il viaggiatore", "le voyageur", "여행자"),
        t("to stop over", "hacer escala", "fazer escala", "fare scalo", "faire escale", "경유하다"),
        t("to stand in line", "hacer cola", "ficar na fila", "fare la coda", "faire la queue", "줄을 서다"),
        t("to hurry", "darse prisa", "se apressar", "sbrigarsi", "faire vite", "서두르다"),
        t("to smoke", "fumar", "fumar", "fumare", "fumer", "피우다"),
        t("to go up", "subir", "subir", "salire", "monter", "올라가다"),
        t("to leave", "salir / irse", "partir", "partire", "partir", "떠나다"),
        t("to be able to", "poder", "poder", "potere", "pouvoir", "할 수 있다"),
        t("to receive", "recibir", "receber", "ricevere", "recevoir", "받다"),
        t("to go out", "salir", "sair", "uscire", "sortir", "나가다"),
        t("to fly / to steal", "volar / robar", "voar / roubar", "volare / rubare", "voler", "날다 / 훔치다"),
        t("to want", "querer", "querer", "volere", "vouloir", "원하다"),
        t("passport", "el pasaporte", "o passaporte", "il passaporto", "le passeport", "여권"),
        t("visa", "el visado", "o visto", "il visto", "le visa", "비자"),
        t("delay", "el retraso", "o atraso", "il ritardo", "le retard", "지연"),
        t("check-in", "el facturación", "o check-in", "il check-in", "l'enregistrement", "체크인"),
        t("security", "la seguridad", "a segurança", "i controlli", "la sûreté", "보안검색"),
        t("gate", "la puerta de embarque", "o portão", "il gate", "la porte d'embarquement", "탑승구"),
        t("one-way", "solo ida", "só ida", "solo andata", "aller simple", "편도"),
        t("window seat", "asiento de ventanilla", "janela", "posto finestrino", "côté hublot", "창가 자리"),
        t("aisle seat", "asiento de pasillo", "corredor", "posto corridoio", "côté couloir", "통로 자리"),
        t("to declare", "declarar", "declarar", "dichiarare", "déclarer", "신고하다"),
        t("overweight bag", "exceso de equipaje", "excesso de bagagem", "eccesso di bagaglio", "excédent de bagages", "초과 수하물"),
        t("terminal", "la terminal", "o terminal", "il terminal", "le terminal", "터미널"),
    ],
    "family": [
        t("friend (m.)", "el amigo", "o amigo", "l'amico", "l'ami", "친구"),
        t("bath", "el baño", "o banho", "il bagno", "le bain", "목욕"),
        t("balcony", "el balcón", "a varanda", "il balcone", "le balcon", "발코니"),
        t("jewels", "las joyas", "as joias", "i gioielli", "les bijoux", "보석"),
        t("truck", "el camión", "o caminhão", "il camion", "le camion", "트럭"),
        t("hallway", "el pasillo", "o corredor", "il corridoio", "le couloir", "복도"),
        t("yard / courtyard", "el patio", "o pátio", "il cortile", "la cour", "마당"),
        t("shower", "la ducha", "o chuveiro", "la doccia", "la douche", "샤워"),
        t("garden", "el jardín", "o jardim", "il giardino", "le jardin", "정원"),
        t("son-in-law", "el yerno", "o genro", "il genero", "le beau-fils", "사위"),
        t("brother-in-law", "el cuñado", "o cunhado", "il cognato", "le beau-frère", "처남/매형"),
        t("parents-in-law", "los suegros", "os sogros", "i suoceri", "les beaux-parents", "시부모/장인어른"),
        t("father-in-law", "el suegro", "o sogro", "il suocero", "le beau-père", "시아버지/장인"),
        t("daughter-in-law", "la nuera", "a nora", "la nuora", "la belle-fille", "며느리"),
        t("mother-in-law", "la suegra", "a sogra", "la suocera", "la belle-mère", "시어머니/장모"),
        t("sister-in-law", "la cuñada", "a cunhada", "la cognata", "la belle-soeur", "시누이/처제"),
        t("cousin (m.)", "el primo", "o primo", "il cugino", "le cousin", "사촌 (남)"),
        t("cousin (f.)", "la prima", "a prima", "la cugina", "la cousine", "사촌 (여)"),
        t("child", "el niño / el hijo", "a criança", "il bambino", "l'enfant", "아이"),
        t("wife / spouse (f.)", "la esposa", "a esposa", "la moglie", "l'épouse", "아내"),
        t("husband / spouse (m.)", "el esposo", "o esposo", "il marito", "l'époux", "남편"),
        t("spouses", "los esposos", "os cônjuges", "gli sposi", "les époux", "부부"),
        t("wife / woman", "la mujer", "a mulher", "la donna / la moglie", "la femme", "아내 / 여자"),
        t("fiancé", "el prometido", "o noivo", "il fidanzato", "le fiancé", "약혼자"),
        t("fiancée", "la prometida", "a noiva", "la fidanzata", "la fiancée", "약혼자"),
        t("washing machine", "la lavadora", "a máquina de lavar", "la lavatrice", "la machine à laver", "세탁기"),
        t("house", "la casa", "a casa", "la casa", "la maison", "집"),
        t("waiting room", "la sala de espera", "a sala de espera", "la sala d'attesa", "la salle d'attente", "대기실"),
        t("bathroom", "el cuarto de baño", "o banheiro", "il bagno", "la salle de bains", "욕실"),
        t("dining room", "el comedor", "a sala de jantar", "la sala da pranzo", "la salle à manger", "식당"),
        t("living room", "el salón", "a sala de estar", "il soggiorno", "le salon", "거실"),
        t("dishes", "la vajilla", "a louça", "le stoviglie", "la vaisselle", "식기"),
        t("neighbor (m.)", "el vecino", "o vizinho", "il vicino", "le voisin", "이웃 (남)"),
        t("neighbor (f.)", "la vecina", "a vizinha", "la vicina", "la voisine", "이웃 (여)"),
        t("son", "el hijo", "o filho", "il figlio", "le fils", "아들"),
        t("brother", "el hermano", "o irmão", "il fratello", "le frère", "형제"),
        t("grandmother", "la abuela", "a avó", "la nonna", "la grand-mère", "할머니"),
        t("grandparents", "los abuelos", "os avós", "i nonni", "les grands-parents", "조부모"),
        t("grandfather", "el abuelo", "o avô", "il nonno", "le grand-père", "할아버지"),
        t("mom", "mamá", "mamãe", "mamma", "maman", "엄마"),
        t("husband", "el marido", "o marido", "il marito", "le mari", "남편"),
        t("mother", "la madre", "a mãe", "la madre", "la mère", "어머니"),
        t("nephew", "el sobrino", "o sobrinho", "il nipote", "le neveu", "조카"),
        t("niece", "la sobrina", "a sobrinha", "la nipote", "la nièce", "조카딸"),
        t("uncle", "el tío", "o tio", "lo zio", "l'oncle", "삼촌"),
        t("father", "el padre", "o pai", "il padre", "le père", "아버지"),
        t("granddaughter", "la nieta", "a neta", "la nipote", "la petite-fille", "손녀"),
        t("grandson", "el nieto", "o neto", "il nipote", "le petit-fils", "손자"),
        t("sister", "la hermana", "a irmã", "la sorella", "la sœur", "자매"),
        t("aunt", "la tía", "a tia", "la zia", "la tante", "이모"),
        t("daughter", "la hija", "a filha", "la figlia", "la fille", "딸"),
        t("parents", "los padres", "os pais", "i genitori", "les parents", "부모"),
        t("baby", "el bebé", "o bebê", "il neonato", "le bébé", "아기"),
        t("dad", "papá", "papai", "papà", "papa", "아빠"),
        t("only child", "hijo único", "filho único", "figlio unico", "fils unique", "외동"),
        t("twins", "los gemelos", "os gêmeos", "i gemelli", "les jumeaux", "쌍둥이"),
        t("kitchen", "la cocina", "a cozinha", "la cucina", "la cuisine", "부엌"),
        t("stairs", "las escaleras", "a escada", "le scale", "l'escalier", "계단"),
        t("dog", "el perro", "o cachorro", "il cane", "le chien", "개"),
        t("cat", "el gato", "o gato", "il gatto", "le chat", "고양이"),
        t("single", "soltero", "solteiro", "celibe / single", "célibataire", "미혼"),
        t("married", "casado", "casado", "sposato", "marié", "기혼"),
        t("family name", "el apellido", "o sobrenome", "il cognome", "le nom de famille", "성"),
        t("first name", "el nombre", "o nome", "il nome", "le prénom", "이름"),
    ],
    "hotel": [
        t("wardrobe", "el armario", "o guarda-roupa", "l'armadio", "l'armoire", "옷장"),
        t("elevator", "el ascensor", "o elevador", "l'ascensore", "l'ascenseur", "엘리베이터"),
        t("library / bookcase", "la biblioteca", "a biblioteca / a estante", "la biblioteca", "la bibliothèque", "책장"),
        t("room", "la habitación", "o quarto", "la camera", "la chambre", "객실"),
        t("key", "la llave", "a chave", "la chiave", "la clé / la clef", "열쇠"),
        t("dresser", "la cómoda", "a cômoda", "il comò", "la commode", "서랍장"),
        t("blanket", "la manta", "o cobertor", "la coperta", "la couverture", "담요"),
        t("sheet", "la sábana", "o lençol", "il lenzuolo", "le drap", "시트"),
        t("water", "el agua", "a água", "l'acqua", "l'eau", "물"),
        t("escape / getaway", "la evasión", "a fuga", "l'evasione", "l'évasion", "탈출"),
        t("maid / housekeeper", "la camarera", "a camareira", "la cameriera", "la femme de chambre", "객실 담당"),
        t("washbasin", "el lavabo", "a pia", "il lavandino", "le lavabo", "세면대"),
        t("bed", "la cama", "a cama", "il letto", "le lit", "침대"),
        t("single bed", "la cama individual", "a cama de solteiro", "il letto singolo", "le lit à une place", "싱글 침대"),
        t("leisure / activities", "el ocio", "o lazer", "il tempo libero", "les loisirs", "여가"),
        t("rent", "el alquiler", "o aluguel", "l'affitto", "le loyer", "임대료"),
        t("mattress", "el colchón", "o colchão", "il materasso", "le matelas", "매트리스"),
        t("sea", "el mar", "o mar", "il mare", "la mer", "바다"),
        t("mountain", "la montaña", "a montanha", "la montagna", "la montagne", "산"),
        t("pillow", "la almohada", "o travesseiro", "il cuscino", "l'oreiller", "베개"),
        t("scenery", "el paisaje", "a paisagem", "il paesaggio", "le paysage", "풍경"),
        t("beach", "la playa", "a praia", "la spiaggia", "la plage", "해변"),
        t("price", "el precio", "o preço", "il prezzo", "le prix", "가격"),
        t("owner", "el dueño", "o proprietário", "il proprietario", "le propriétaire", "주인"),
        t("front desk", "la recepción", "a recepção", "la reception", "la réception", "프론트"),
        t("ground floor", "la planta baja", "o térreo", "il pianoterra", "le rez-de-chaussée", "1층"),
        t("soap", "el jabón", "o sabonete", "il sapone", "le savon", "비누"),
        t("towel", "la toalla", "a toalha", "l'asciugamano", "la serviette", "수건"),
        t("sun", "el sol", "o sol", "il sole", "le soleil", "해"),
        t("pillowcase", "la funda", "a fronha", "la federa", "la taie d'oreiller", "베갯잇"),
        t("rug", "la alfombra", "o tapete", "il tappeto", "le tapis", "러그"),
        t("treasure", "el tesoro", "o tesouro", "il tesoro", "le trésor", "보물"),
        t("clothing", "la ropa", "a roupa", "i vestiti", "les vêtements", "옷"),
        t("to notify", "avisar", "avisar", "avvertire", "avertir", "알리다"),
        t("to have fun", "divertirse", "se divertir", "divertirsi", "s'amuser", "즐기다"),
        t("to dial / compose", "marcar / componer", "digitar / compor", "comporre", "composer", "누르다"),
        t("to become", "volverse / hacerse", "tornar-se", "diventare", "devenir", "되다"),
        t("separate / aside", "aparte", "à parte", "a parte", "à part", "따로"),
        t("in other words", "dicho de otro modo", "em outras palavras", "in altre parole", "autrement dit", "다시 말해"),
        t("noisy", "ruidoso", "barulhento", "rumoroso", "bruyant", "시끄러운"),
        t("available", "disponible", "disponível", "disponibile", "disponible", "가능한"),
        t("bad / mean", "malo / malo", "mau", "cattivo", "mauvais", "나쁜"),
        t("to say", "decir", "dizer", "dire", "dire", "말하다"),
        t("to sleep", "dormir", "dormir", "dormire", "dormir", "자다"),
        t("to leave / quit", "dejar / salir", "sair / deixar", "lasciare", "quitter", "떠나다"),
        t("to tease", "tomar el pelo", "caçoar", "prendere in giro", "taquiner", "놀리다"),
        t("furnished", "amueblado", "mobiliado", "arredato", "meublé", "가구가 있는"),
        t("cloudy", "nublado", "nublado", "nuvoloso", "nuageux", "흐린"),
        t("by chance", "por casualidad", "por acaso", "per caso", "par hasard", "우연히"),
        t("next", "próximo / siguiente", "próximo", "prossimo", "prochain", "다음"),
        t("reservation", "la reserva", "a reserva", "la prenotazione", "la réservation", "예약"),
        t("breakfast", "el desayuno", "o café da manhã", "la colazione", "le petit-déjeuner", "아침 식사"),
        t("wifi", "el wifi", "o wi-fi", "il wifi", "le wifi", "와이파이"),
        t("floor (story)", "el piso", "o andar", "il piano", "l'étage", "층"),
        t("air conditioning", "el aire acondicionado", "o ar-condicionado", "l'aria condizionata", "la climatisation", "에어컨"),
        t("swimming pool", "la piscina", "a piscina", "la piscina", "la piscine", "수영장"),
        t("double room", "habitación doble", "quarto de casal", "camera doppia", "chambre double", "더블룸"),
        t("view", "la vista", "a vista", "la vista", "la vue", "전망"),
        t("check-in", "el registro de entrada", "o check-in", "il check-in", "l'arrivée", "체크인"),
        t("check-out", "la salida", "o check-out", "il check-out", "le départ", "체크아웃"),
        t("safe", "la caja fuerte", "o cofre", "la cassaforte", "le coffre-fort", "금고"),
        t("room number", "el número de habitación", "o número do quarto", "il numero di camera", "le numéro de chambre", "객실 번호"),
    ],
    "birthday": [
        t("appetizers", "los aperitivos", "os petiscos", "gli stuzzichini", "les amuse-gueules", "전채"),
        t("birthday", "el cumpleaños", "o aniversário", "il compleanno", "l'anniversaire", "생일"),
        t("chatter / gossip", "el cotilleo", "a fofoca", "i pettegolezzi", "le bavardage", "수다"),
        t("Sunday", "el domingo", "o domingo", "la domenica", "le dimanche", "일요일"),
        t("party", "la fiesta", "a festa", "la festa", "la fête", "파티"),
        t("fridge", "la nevera", "a geladeira", "il frigo", "le frigo", "냉장고"),
        t("cheese", "el queso", "o queijo", "il formaggio", "le fromage", "치즈"),
        t("ice cubes", "los cubitos", "os cubos de gelo", "i cubetti", "les glaçons", "얼음"),
        t("strike", "la huelga", "a greve", "lo sciopero", "la grève", "파업"),
        t("honor", "el honor", "a honra", "l'onore", "l'honneur", "명예"),
        t("joy", "la alegría", "a alegria", "la gioia", "la joie", "기쁨"),
        t("July", "julio", "julho", "luglio", "juillet", "7월"),
        t("Monday", "el lunes", "a segunda", "il lunedì", "lundi", "월요일"),
        t("Tuesday", "el martes", "a terça", "il martedì", "mardi", "화요일"),
        t("morning", "la mañana", "a manhã", "il mattino", "le matin", "아침"),
        t("mix", "la mezcla", "a mistura", "la miscela", "le mélange", "혼합"),
        t("fashionable", "de moda", "na moda", "alla moda", "à la mode", "유행하는"),
        t("pastime", "el pasatiempo", "o passatempo", "il passatempo", "le passe-temps", "취미"),
        t("progress", "el progreso", "o progresso", "il progresso", "le progrès", "진전"),
        t("diet", "la dieta", "a dieta", "la dieta", "le régime", "식단"),
        t("information", "la información", "as informações", "le informazioni", "les renseignements", "정보"),
        t("rhythm", "el ritmo", "o ritmo", "il ritmo", "le rythme", "리듬"),
        t("feeling", "el sentimiento", "o sentimento", "il sentimento", "le sentiment", "감정"),
        t("face", "la cara", "o rosto", "il viso", "le visage", "얼굴"),
        t("car", "el coche", "o carro", "la macchina", "la voiture", "차"),
        t("will (n.)", "la voluntad", "a vontade", "la volontà", "la volonté", "의지"),
        t("to chat", "charlar", "conversar", "chiacchierare", "bavarder", "수다 떨다"),
        t("to guess", "adivinar", "adivinhar", "indovinare", "deviner", "맞히다"),
        t("to celebrate", "festejar", "comemorar", "festeggiare", "fêter", "축하하다"),
        t("to win / earn", "ganar", "ganhar", "vincere / guadagnare", "gagner", "이기다"),
        t("to miss / lack", "echar de menos / faltar", "sentir falta / faltar", "mancare", "manquer", "보고 싶다 / 부족하다"),
        t("to thank", "agradecer", "agradecer", "ringraziare", "remercier", "감사하다"),
        t("to look like", "parecerse", "se parecer", "assomigliare", "ressembler", "닮다"),
        t("to dream", "soñar", "sonhar", "sognare", "rêver", "꿈꾸다"),
        t("to laugh", "reír", "rir", "ridere", "rire", "웃다"),
        t("to end", "terminar", "terminar", "terminare", "terminer", "끝내다"),
        t("to unite", "unir", "unir", "unire", "unir", "하나로 하다"),
        t("to be willing", "estar dispuesto", "estar disposto", "essere disposto", "vouloir bien", "기꺼이 하다"),
        t("gift", "el regalo", "o presente", "il regalo", "le cadeau", "선물"),
        t("cake", "la tarta", "o bolo", "la torta", "le gâteau", "케이크"),
        t("candle", "la vela", "a vela", "la candelina", "la bougie", "촛불"),
        t("wish", "el deseo", "o pedido", "il desiderio", "le vœu", "소원"),
        t("guest", "el invitado", "o convidado", "l'ospite", "l'invité", "손님"),
        t("to invite", "invitar", "convidar", "invitare", "inviter", "초대하다"),
        t("balloon", "el globo", "o balão", "il palloncino", "le ballon", "풍선"),
        t("song", "la canción", "a canção", "la canzone", "la chanson", "노래"),
        t("age", "la edad", "a idade", "l'età", "l'âge", "나이"),
        t("Wednesday", "el miércoles", "a quarta", "il mercoledì", "mercredi", "수요일"),
        t("Thursday", "el jueves", "a quinta", "il giovedì", "jeudi", "목요일"),
        t("Friday", "el viernes", "a sexta", "il venerdì", "vendredi", "금요일"),
        t("Saturday", "el sábado", "o sábado", "il sabato", "samedi", "토요일"),
        t("how old?", "¿cuántos años?", "quantos anos?", "quanti anni?", "quel âge ?", "몇 살?"),
        t("congratulations", "enhorabuena", "parabéns", "congratulazioni", "félicitations", "축하해"),
        t("to blow out", "soplar", "soprar", "soffiare", "souffler", "불다"),
        t("champagne", "el champán", "o champanhe", "lo spumante", "le champagne", "샴페인"),
        t("dance", "el baile", "a dança", "il ballo", "la danse", "춤"),
        t("to hug", "abrazar", "abraçar", "abbracciare", "embrasser / câliner", "안다"),
        t("friend", "el amigo", "o amigo", "l'amico", "l'ami", "친구"),
        t("happy birthday", "feliz cumpleaños", "feliz aniversário", "buon compleanno", "joyeux anniversaire", "생일 축하해"),
    ],
    "grocery": [
        t("lamb", "el cordero", "o cordeiro", "l'agnello", "l'agneau", "양고기"),
        t("garlic", "el ajo", "o alho", "l'aglio", "l'ail", "마늘"),
        t("plate / dish", "el plato", "o prato", "il piatto", "l'assiette", "접시"),
        t("butter", "la mantequilla", "a manteiga", "il burro", "le beurre", "버터"),
        t("steak", "el bistec", "o bife", "la bistecca", "le bifteck", "스테이크"),
        t("beef", "la carne de vacuno", "a carne bovina", "il manzo", "le bœuf", "소고기"),
        t("bottle", "la botella", "a garrafa", "la bottiglia", "la bouteille", "병"),
        t("customer", "el cliente", "o cliente", "il cliente", "le client", "손님"),
        t("turkey", "el pavo", "o peru", "il tacchino", "la dinde", "칠면조"),
        t("mineral water", "el agua mineral", "a água mineral", "l'acqua minerale", "l'eau minérale", "생수"),
        t("spices", "las especias", "as especiarias", "le spezie", "les épices", "향신료"),
        t("flour", "la harina", "a farinha", "la farina", "la farine", "밀가루"),
        t("strawberries", "las fresas", "os morangos", "le fragole", "les fraises", "딸기"),
        t("manager", "el gerente", "o gerente", "il gerente", "le gérant", "매니저"),
        t("green beans", "las judías verdes", "o vagem", "i fagiolini", "les haricots verts", "풋콩"),
        t("oil", "el aceite", "o óleo / azeite", "l'olio", "l'huile", "기름"),
        t("orange juice", "el zumo de naranja", "o suco de laranja", "il succo d'arancia", "le jus d'orange", "오렌지 주스"),
        t("milk", "la leche", "o leite", "il latte", "le lait", "우유"),
        t("shopkeeper", "el tendero", "o comerciante", "il negoziante", "le marchand", "가게 주인"),
        t("egg", "el huevo", "o ovo", "l'uovo", "l'œuf", "계란"),
        t("onion", "la cebolla", "a cebola", "la cipolla", "l'oignon", "양파"),
        t("bread", "el pan", "o pão", "il pane", "le pain", "빵"),
        t("peas", "los guisantes", "as ervilhas", "i piselli", "les petits pois", "완두콩"),
        t("pear", "la pera", "a pera", "la pera", "la poire", "배"),
        t("pepper (spice)", "la pimienta", "a pimenta", "il pepe", "le poivre", "후추"),
        t("salt", "la sal", "o sal", "il sale", "le sel", "소금"),
        t("sugar", "el azúcar", "o açúcar", "lo zucchero", "le sucre", "설탕"),
        t("to sharpen", "afilar", "afiar", "affilare", "aiguiser", "갈다"),
        t("to stop (oneself)", "detenerse", "parar", "fermarsi", "s'arrêter", "멈추다"),
        t("to boil", "hervir", "ferver", "bollire", "bouillir", "끓이다"),
        t("to cook", "cocinar / cocer", "cozinhar", "cucinare / cuocere", "cuire", "요리하다"),
        t("to patronize / frequent", "frecuentar", "frequentar", "frequentare", "fréquenter", "단골로 가다"),
        t("to manage", "gestionar", "gerir", "gestire", "gérer", "운영하다"),
        t("to deliver", "entregar", "entregar", "consegnare", "livrer", "배달하다"),
        t("to waste time", "perder el tiempo", "perder tempo", "perdere tempo", "perdre son temps", "시간을 낭비하다"),
        t("to joke", "bromear", "brincar", "scherzare", "plaisanter", "농담하다"),
        t("to give change", "devolver el cambio", "dar o troco", "dare il resto", "rendre la monnaie", "거스름돈을 주다"),
        t("to serve", "servir", "servir", "servire", "servir", "서빙하다"),
        t("to suppress / cut", "suprimir", "suprimir", "sopprimere", "supprimer", "없애다"),
        t("to cheat / deceive", "engañar", "enganar", "ingannare", "tromper", "속이다"),
        t("to sell", "vender", "vender", "vendere", "vendre", "팔다"),
        t("to check / verify", "verificar", "verificar", "verificare", "vérifier", "확인하다"),
        t("to steal / to fly", "robar / volar", "roubar / voar", "rubare / volare", "voler", "훔치다 / 날다"),
        t("baguette", "la barra de pan", "a baguete", "la baguette", "la baguette", "바게트"),
        t("tomato", "el tomate", "o tomate", "il pomodoro", "la tomate", "토마토"),
        t("cheese", "el queso", "o queijo", "il formaggio", "le fromage", "치즈"),
        t("rice", "el arroz", "o arroz", "il riso", "le riz", "쌀"),
        t("yogurt", "el yogur", "o iogurte", "lo yogurt", "le yaourt", "요거트"),
        t("apple", "la manzana", "a maçã", "la mela", "la pomme", "사과"),
        t("banana", "el plátano", "a banana", "il banana / il banano", "la banane", "바나나"),
        t("potato", "la patata", "a batata", "la patata", "la pomme de terre", "감자"),
        t("carrot", "la zanahoria", "a cenoura", "la carota", "la carotte", "당근"),
        t("coffee", "el café", "o café", "il caffè", "le café", "커피"),
        t("tea", "el té", "o chá", "il tè", "le thé", "차"),
        t("shopping cart", "el carrito", "o carrinho", "il carrello", "le caddie", "카트"),
        t("organic", "ecológico / orgánico", "orgânico", "biologico", "bio", "유기농"),
        t("kilo", "el kilo", "o quilo", "il chilo", "le kilo", "킬로"),
        t("fresh", "fresco", "fresco", "fresco", "frais", "신선한"),
        t("frozen", "congelado", "congelado", "surgelato", "surgelé", "냉동"),
        t("market", "el mercado", "o mercado", "il mercato", "le marché", "시장"),
        t("to weigh", "pesar", "pesar", "pesare", "peser", "무게를 재다"),
        t("change (money)", "el cambio", "o troco", "il resto", "la monnaie", "거스름돈"),
        t("queue", "la cola", "a fila", "la coda", "la queue", "줄"),
        t("closed on Sunday", "cerrado el domingo", "fechado domingo", "chiuso la domenica", "fermé le dimanche", "일요일 휴무"),
    ],
    "bank": [
        t("stock / share", "la acción", "a ação", "l'azione", "l'action", "주식"),
        t("shareholder", "el accionista", "o acionista", "l'azionista", "l'actionnaire", "주주"),
        t("business", "el negocio", "o negócio", "l'affare / l'azienda", "l'affaire", "사업"),
        t("broker", "el corredor", "o corretor", "il broker", "l'agent de change", "중개인"),
        t("banker", "el banquero", "o banqueiro", "il banchiere", "le banquier", "은행가"),
        t("money order", "el giro", "a ordem de pagamento", "il vaglia", "le mandat", "환어음"),
        t("cashier's office", "la caja", "o caixa", "la cassa", "la caisse", "창구"),
        t("teller", "el cajero", "o caixa", "il cassiere", "le caissier", "출납원"),
        t("safe-deposit box", "la caja de seguridad", "o cofre", "la cassetta di sicurezza", "le coffre", "금고"),
        t("cash", "el efectivo", "o dinheiro vivo", "il contante", "le comptant", "현금"),
        t("credit", "el crédito", "o crédito", "il credito", "le crédit", "신용"),
        t("foreign currency", "las divisas", "o câmbio", "le valute", "les devises", "외환"),
        t("exchange", "el cambio", "o câmbio", "il cambio", "l'échange", "환전"),
        t("loan", "el préstamo", "o empréstimo", "il prestito", "l'emprunt", "대출"),
        t("savings", "el ahorro", "a poupança", "il risparmio", "l'épargne", "저축"),
        t("capital / funds", "los fondos", "os fundos", "i fondi", "les fonds", "자본"),
        t("teller window", "la ventanilla", "o guichê", "lo sportello", "le guichet", "창구"),
        t("mortgage", "la hipoteca", "a hipoteca", "il mutuo", "l'hypothèque", "담보 대출"),
        t("tax", "el impuesto", "o imposto", "la tassa", "l'impôt", "세금"),
        t("interest", "el interés", "os juros", "l'interesse", "l'intérêt", "이자"),
        t("checkbook", "la chequera", "o talão de cheques", "il libretto degli assegni", "le carnet de chèques", "수표책"),
        t("month", "el mes", "o mês", "il mese", "le mois", "달"),
        t("amount", "el importe", "o valor", "l'importo", "le montant", "금액"),
        t("investment", "la inversión", "o investimento", "l'investimento", "le placement", "투자"),
        t("salary / wages", "el sueldo", "o salário", "lo stipendio", "le salaire", "월급"),
        t("week", "la semana", "a semana", "la settimana", "la semaine", "주"),
        t("branch", "la sucursal", "a agência", "la filiale", "la succursale", "지점"),
        t("rate / percentage", "el tipo / el porcentaje", "a taxa", "il tasso", "le taux", "이율"),
        t("value", "el valor", "o valor", "il valore", "la valeur", "가치"),
        t("payment", "el pago / el ingreso", "o pagamento", "il versamento", "le versement", "납입"),
        t("to raise / increase", "aumentar", "aumentar", "aumentare", "augmenter", "올리다"),
        t("to lower", "bajar", "baixar", "abbassare", "baisser", "내리다"),
        t("to discover", "descubrir", "descobrir", "scoprire", "découvrir", "발견하다"),
        t("to deposit", "ingresar", "depositar", "depositare", "déposer", "입금하다"),
        t("to save (money)", "ahorrar", "economizar", "risparmiare", "économiser", "저축하다"),
        t("to borrow", "pedir prestado", "pedir emprestado", "prendere in prestito", "emprunter", "빌리다"),
        t("to put aside", "ahorrar", "poupar", "mettere da parte", "épargner", "모아 두다"),
        t("to be broke", "estar sin blanca", "estar liso", "essere al verde", "être à sec", "돈이 없다"),
        t("to earn / win", "ganar", "ganhar", "guadagnare", "gagner", "벌다"),
        t("to leave", "dejar", "deixar", "lasciare", "laisser", "남기다"),
        t("to pay cash", "pagar al contado", "pagar à vista", "pagare in contanti", "payer comptant", "현금으로 내다"),
        t("to invest", "invertir", "investir", "investire", "placer", "투자하다"),
        t("to complain", "quejarse", "reclamar", "lamentarsi", "se plaindre", "불평하다"),
        t("to please", "gustar / agradar", "agradar", "piacere", "plaire", "기쁘게 하다"),
        t("to lend", "prestar", "emprestar", "prestare", "prêter", "빌려주다"),
        t("to withdraw", "sacar", "sacar", "prelevare", "tirer / retirer", "출금하다"),
        t("to cash (a check)", "cobrar", "descontar", "incassare", "toucher", "현금화하다"),
        t("to be worth", "valer", "valer", "valere", "valoir", "가치가 있다"),
        t("account", "la cuenta", "a conta", "il conto", "le compte", "계좌"),
        t("ATM", "el cajero", "o caixa eletrônico", "il bancomat", "le distributeur", "현금인출기"),
        t("bank card", "la tarjeta bancaria", "o cartão do banco", "la carta bancomat", "la carte bancaire", "체크카드"),
        t("PIN", "el PIN", "a senha", "il PIN", "le code secret", "비밀번호"),
        t("transfer", "la transferencia", "a transferência", "il bonifico", "le virement", "이체"),
        t("balance", "el saldo", "o saldo", "il saldo", "le solde", "잔액"),
        t("overdraft", "el descubierto", "o cheque especial", "lo scoperto", "le découvert", "마이너스 통장"),
        t("to open an account", "abrir una cuenta", "abrir uma conta", "aprire un conto", "ouvrir un compte", "계좌를 열다"),
        t("exchange rate", "el tipo de cambio", "a cotação", "il tasso di cambio", "le taux de change", "환율"),
        t("dollar", "el dólar", "o dólar", "il dollaro", "le dollar", "달러"),
        t("euro", "el euro", "o euro", "l'euro", "l'euro", "유로"),
        t("receipt", "el justificante", "o comprovante", "la ricevuta", "le reçu", "영수증"),
        t("identity papers", "el documento", "o documento", "il documento", "la pièce d'identité", "신분증"),
        t("to sign", "firmar", "assinar", "firmare", "signer", "서명하다"),
        t("counter", "el mostrador", "o balcão", "il banco", "le comptoir", "카운터"),
        t("queue ticket", "el número de turno", "a senha", "il numeretto", "le ticket", "대기표"),
    ],
    "train": [
        t("trunk (car)", "el maletero", "o porta-malas", "il bagagliaio", "le coffre", "트렁크"),
        t("ticket collector", "el revisor", "o cobrador", "il controllore", "le contrôleur", "차장"),
        t("berth / bunk", "la litera", "a beliche", "la cuccetta", "la couchette", "침대 칸 침대"),
        t("place", "el lugar", "o lugar", "il posto", "l'endroit", "곳"),
        t("east", "el este", "o leste", "l'est", "l'est", "동쪽"),
        t("rush hour", "la hora punta", "o horário de pico", "l'ora di punta", "l'heure d'affluence", "러시아워"),
        t("schedule / timetable", "el horario", "o horário", "l'orario", "l'horaire", "시간표"),
        t("engineer (train)", "el maquinista", "o maquinista", "il macchinista", "le machiniste", "기관사"),
        t("trunk (suitcase)", "el baúl", "o baú", "il baule", "la malle", "트렁크 가방"),
        t("brand", "la marca", "a marca", "la marca", "la marque", "브랜드"),
        t("means / way", "el medio", "o meio", "il mezzo", "le moyen", "수단"),
        t("north", "el norte", "o norte", "il nord", "le nord", "북쪽"),
        t("night", "la noche", "a noite", "la notte", "la nuit", "밤"),
        t("west", "el oeste", "o oeste", "l'ovest", "l'ouest", "서쪽"),
        t("road sign", "la señal", "a placa", "il cartello", "le panneau", "도로 표지"),
        t("platform", "el andén", "a plataforma", "il binario / il marciapiede", "le quai", "승강장"),
        t("highway", "la carretera nacional", "a rodovia", "la statale", "la route nationale", "국도"),
        t("exit", "la salida", "a saída", "l'uscita", "la sortie", "출구"),
        t("station / stop", "la estación / parada", "a estação / parada", "la stazione / fermata", "la station", "정거장"),
        t("south", "el sur", "o sul", "il sud", "le sud", "남쪽"),
        t("speed", "la velocidad", "a velocidade", "la velocità", "la vitesse", "속도"),
        t("baggage car", "el furgón", "o vagão de bagagem", "il bagagliaio", "le wagon aux bagages", "수하물 칸"),
        t("sleeping car", "el coche cama", "o vagão-leito", "la carrozza letto", "le wagon-lit", "침대 칸"),
        t("dining car", "el coche restaurante", "o vagão-restaurante", "la carrozza ristorante", "le wagon-restaurant", "식당 칸"),
        t("to drive", "conducir", "dirigir", "guidare", "conduire", "운전하다"),
        t("to run", "correr", "correr", "correre", "courir", "달리다"),
        t("to fall asleep", "dormirse", "adormecer", "addormentarsi", "s'endormir", "잠들다"),
        t("to be in a hurry", "tener prisa", "estar com pressa", "avere fretta", "être pressé", "급하다"),
        t("to indicate", "indicar", "indicar", "indicare", "indiquer", "가리키다"),
        t("to go up / get on", "subir", "subir", "salire", "monter", "타다"),
        t("to forget", "olvidar", "esquecer", "dimenticare", "oublier", "잊다"),
        t("together", "juntos", "juntos", "insieme", "ensemble", "함께"),
        t("abroad", "en el extranjero", "no exterior", "all'estero", "à l'étranger", "해외에서"),
        t("in shape", "en forma", "em forma", "in forma", "en forme", "컨디션이 좋은"),
        t("on time", "en hora / puntual", "no horário", "in orario", "à l'heure", "제시간에"),
        t("to tell (a story)", "contar", "contar", "raccontare", "raconter", "이야기하다"),
        t("to return home", "volver a casa", "voltar para casa", "rincasare", "rentrer", "귀가하다"),
        t("to leave again", "volver a salir", "partir de novo", "ripartire", "repartir", "다시 떠나다"),
        t("to return", "regresar", "retornar", "ritornare", "retourner", "돌아가다"),
        t("to feel", "sentirse", "se sentir", "sentirsi", "se sentir", "느끼다"),
        t("to fall", "caerse", "cair", "cadere", "tomber", "떨어지다"),
        t("incredible", "increíble", "incrível", "incredibile", "incroyable", "믿을 수 없는"),
        t("several", "varios", "vários", "parecchi", "plusieurs", "여러"),
        t("rather", "más bien", "antes / preferencialmente", "piuttosto", "plutôt", "오히려"),
        t("train", "el tren", "o trem", "il treno", "le train", "기차"),
        t("ticket", "el billete", "a passagem", "il biglietto", "le billet", "표"),
        t("connection", "el transbordo", "a conexão", "la coincidenza", "la correspondance", "환승"),
        t("delay", "el retraso", "o atraso", "il ritardo", "le retard", "지연"),
        t("track / platform number", "la vía", "a plataforma", "il binario", "la voie", "선로"),
        t("compartment", "el compartimento", "o compartimento", "lo scompartimento", "le compartiment", "칸"),
        t("high-speed train", "el AVE / tren de alta velocidad", "o trem-bala", "l'alta velocità", "le TGV", "고속열차"),
        t("to miss (a train)", "perder", "perder", "perdere", "rater", "놓치다"),
        t("to get off", "bajar", "descer", "scendere", "descendre", "내리다"),
        t("seat", "el asiento", "o assento", "il posto", "la place", "자리"),
        t("left", "izquierda", "esquerda", "sinistra", "gauche", "왼쪽"),
        t("right", "derecha", "direita", "destra", "droite", "오른쪽"),
        t("next train", "el próximo tren", "o próximo trem", "il prossimo treno", "le prochain train", "다음 기차"),
        t("lost and found", "objetos perdidos", "achados e perdidos", "oggetti smarriti", "objets trouvés", "분실물 센터"),
        t("waiting room", "la sala de espera", "a sala de espera", "la sala d'attesa", "la salle d'attente", "대기실"),
        t("to validate a ticket", "validar el billete", "validar a passagem", "obliterare il biglietto", "composter le billet", "표를 찍다"),
        t("season ticket", "el abono", "o passe", "l'abbonamento", "l'abonnement", "정기권"),
        t("subway", "el metro", "o metrô", "la metropolitana", "le métro", "지하철"),
        t("bus", "el autobús", "o ônibus", "l'autobus", "le bus", "버스"),
    ],
    "body": [
        t("beard", "la barba", "a barba", "la barba", "la barbe", "수염"),
        t("mouth", "la boca", "a boca", "la bocca", "la bouche", "입"),
        t("arm", "el brazo", "o braço", "il braccio", "le bras", "팔"),
        t("pest / pain (person)", "el pesado", "o chato", "il rompiscatole", "le casse-pieds", "성가신 사람"),
        t("hair", "el pelo", "o cabelo", "i capelli", "les cheveux", "머리카락"),
        t("ankle", "el tobillo", "o tornozelo", "la caviglia", "la cheville", "발목"),
        t("eyelash", "la pestaña", "o cílio", "la ciglia", "le cil", "속눈썹"),
        t("advice", "el consejo", "o conselho", "il consiglio", "le conseil", "조언"),
        t("body", "el cuerpo", "o corpo", "il corpo", "le corps", "몸"),
        t("neck", "el cuello", "o pescoço", "il collo", "le cou", "목"),
        t("tooth", "el diente", "o dente", "il dente", "la dent", "이"),
        t("finger", "el dedo", "o dedo", "il dito", "le doigt", "손가락"),
        t("back", "la espalda", "as costas", "la schiena", "le dos", "등"),
        t("shoulder", "el hombro", "o ombro", "la spalla", "l'épaule", "어깨"),
        t("stomach", "el estómago", "o estômago", "lo stomaco", "l'estomac", "위"),
        t("liver", "el hígado", "o fígado", "il fegato", "le foie", "간"),
        t("forehead", "la frente", "a testa", "la fronte", "le front", "이마"),
        t("knee", "la rodilla", "o joelho", "il ginocchio", "le genou", "무릎"),
        t("throat", "la garganta", "a garganta", "la gola", "la gorge", "목구멍"),
        t("leg", "la pierna", "a perna", "la gamba", "la jambe", "다리"),
        t("tongue", "la lengua", "a língua", "la lingua", "la langue", "혀"),
        t("hand", "la mano", "a mão", "la mano", "la main", "손"),
        t("chin", "la barbilla", "o queixo", "il mento", "le menton", "턱"),
        t("nose", "la nariz", "o nariz", "il naso", "le nez", "코"),
        t("eye", "el ojo", "o olho", "l'occhio", "l'œil", "눈"),
        t("ear", "la oreja", "a orelha", "l'orecchio", "l'oreille", "귀"),
        t("foot", "el pie", "o pé", "il piede", "le pied", "발"),
        t("chest", "el pecho", "o peito", "il petto", "la poitrine", "가슴"),
        t("lung", "el pulmón", "o pulmão", "il polmone", "le poumon", "폐"),
        t("health", "la salud", "a saúde", "la salute", "la santé", "건강"),
        t("eyebrow", "la ceja", "a sobrancelha", "il sopracciglio", "le sourcil", "눈썹"),
        t("smile", "la sonrisa", "o sorriso", "il sorriso", "le sourire", "미소"),
        t("belly / abdomen", "el vientre", "a barriga", "la pancia", "le ventre", "배"),
        t("face", "la cara", "o rosto", "il viso", "le visage", "얼굴"),
        t("eyes", "los ojos", "os olhos", "gli occhi", "les yeux", "눈 (복수)"),
        t("to break", "romper", "quebrar", "rompere", "casser", "부러뜨리다"),
        t("to heal", "curar", "curar", "guarire", "guérir", "낫다"),
        t("to put / place", "poner", "pôr", "mettere", "poser", "놓다"),
        t("to rest", "descansar", "descansar", "riposarsi", "se reposer", "쉬다"),
        t("to put back", "volver a poner", "repor", "ripore", "reposer", "다시 놓다"),
        t("to breathe", "respirar", "respirar", "respirare", "respirer", "숨 쉬다"),
        t("to wake up", "despertarse", "acordar", "svegliarsi", "se réveiller", "일어나다"),
        t("to feel", "sentirse", "se sentir", "sentirsi", "se sentir", "느끼다"),
        t("to take care of", "cuidar", "cuidar", "curare", "soigner", "돌보다"),
        t("to get sick", "enfermarse", "ficar doente", "ammalarsi", "tomber malade", "병에 걸리다"),
        t("to cough", "toser", "tossir", "tossire", "tousser", "기침하다"),
        t("to trip", "tropezar", "tropeçar", "inciampare", "trébucher", "발이 걸리다"),
        t("to find oneself", "encontrarse", "se encontrar", "trovarsi", "se trouver", "있다"),
        t("heart", "el corazón", "o coração", "il cuore", "le cœur", "심장"),
        t("head", "la cabeza", "a cabeça", "la testa", "la tête", "머리"),
        t("blood", "la sangre", "o sangue", "il sangue", "le sang", "피"),
        t("skin", "la piel", "a pele", "la pelle", "la peau", "피부"),
        t("brain", "el cerebro", "o cérebro", "il cervello", "le cerveau", "뇌"),
        t("bone", "el hueso", "o osso", "l'osso", "l'os", "뼈"),
        t("muscle", "el músculo", "o músculo", "il muscolo", "le muscle", "근육"),
        t("wrist", "la muñeca", "o pulso", "il polso", "le poignet", "손목"),
        t("hip", "la cadera", "o quadril", "l'anca", "la hanche", "엉덩이뼈"),
        t("thumb", "el pulgar", "o polegar", "il pollice", "le pouce", "엄지"),
        t("it hurts", "duele", "doi", "fa male", "ça fait mal", "아프다"),
        t("headache", "el dolor de cabeza", "a dor de cabeça", "il mal di testa", "le mal de tête", "두통"),
        t("to bleed", "sangrar", "sangrar", "sanguinare", "saigner", "피가 나다"),
        t("left / right (body)", "izquierdo / derecho", "esquerdo / direito", "sinistro / destro", "gauche / droit", "왼쪽 / 오른쪽"),
    ],
    "health": [
        t("food / diet (intake)", "la alimentación", "a alimentação", "l'alimentazione", "l'alimentation", "식사/영양"),
        t("scale", "la báscula", "a balança", "la bilancia", "la balance", "체중계"),
        t("barber", "el barbero", "o barbeiro", "il barbiere", "le barbier", "이발사"),
        t("butcher's", "la carnicería", "o açougue", "la macelleria", "la boucherie", "정육점"),
        t("bakery", "la panadería", "a padaria", "la panetteria", "la boulangerie", "빵집"),
        t("brush (tooth/hair)", "el cepillo", "a escova", "lo spazzolino / la spazzola", "la brosse", "솔"),
        t("sedative", "el calmante", "o calmante", "il calmante", "le calmant", "진정제"),
        t("eyedropper", "el cuentagotas", "o conta-gotas", "il contagocce", "le compte-goutte", "스포이드"),
        t("attack / crisis", "la crisis", "a crise", "la crisi", "la crise", "발작 / 위기"),
        t("diet (restrictive)", "la dieta", "a dieta", "la dieta", "la diète", "식이요법"),
        t("drug", "la droga / el fármaco", "a droga / o remédio", "la droga / il farmaco", "la drogue", "약 / 마약"),
        t("hope", "la esperanza", "a esperança", "la speranza", "l'espoir", "희망"),
        t("drop", "la gota", "a gota", "la goccia", "la goutte", "방울"),
        t("razor blade", "la cuchilla", "a lâmina", "la lametta", "la lame", "면도날"),
        t("comb", "el peine", "o pente", "il pettine", "le peigne", "빗"),
        t("pipe", "la pipa", "o cachimbo", "la pipa", "la pipe", "파이프"),
        t("cast / plaster", "la escayola", "o gesso", "il gesso", "le plâtre", "깁스"),
        t("filling (tooth)", "el empaste", "a obturação", "l'otturazione", "le plombage", "충치 치료"),
        t("fish market", "la pescadería", "a peixaria", "la pescheria", "la poissonnerie", "생선 가게"),
        t("powder", "el polvo", "o pó", "la polvere", "la poudre", "가루"),
        t("razor", "la maquinilla", "o barbeador", "il rasoio", "le rasoir", "면도기"),
        t("diet / regimen", "el régimen", "o regime", "il regime", "le régime", "식이"),
        t("relief", "el alivio", "o alívio", "il sollievo", "le soulagement", "완화"),
        t("syrup", "el jarabe", "o xarope", "lo sciroppo", "le sirop", "시럽"),
        t("talc", "el talco", "o talco", "il talco", "le talc", "베이비파우더"),
        t("to abuse", "abusar", "abusar", "abusare", "abuser", "남용하다"),
        t("to feed", "alimentar", "alimentar", "alimentare", "alimenter", "먹이다"),
        t("to swallow", "tragar", "engolir", "inghiottire", "avaler", "삼키다"),
        t("to owe to", "deber a", "dever a", "dovere a", "devoir à", "~덕분이다"),
        t("to last", "durar", "durar", "durare", "durer", "지속하다"),
        t("to listen", "escuchar", "escutar", "ascoltare", "écouter", "듣다"),
        t("to balance", "equilibrar", "equilibrar", "equilibrare", "équilibrer", "균형을 맞추다"),
        t("complicated", "complicado", "complicado", "complicato", "compliqué", "복잡한"),
        t("thanks to", "gracias a", "graças a", "grazie a", "grâce à", "~덕분에"),
        t("fat (greasy)", "graso", "gorduroso", "grasso", "gras", "기름진"),
        t("fat / big", "gordo / grueso", "gordo / grosso", "grasso / grosso", "gros", "뚱뚱한"),
        t("stainless / rustproof", "inoxidable", "inoxidável", "inossidabile", "inoxydable", "녹슬지 않는"),
        t("a long time", "mucho tiempo", "muito tempo", "a lungo", "longtemps", "오랫동안"),
        t("to gain weight", "engordar", "engordar", "ingrassare", "grossir", "살찌다"),
        t("to get used to", "acostumbrarse", "se acostumar", "abituarsi", "s'habituer", "익숙해지다"),
        t("to pass / happen", "pasar", "passar", "passare", "(se) passer", "지나다"),
        t("to fill (a tooth)", "empastar", "obter / preencher", "otturare", "plomber", "이를 메우다"),
        t("to shave", "afeitarse", "fazer a barba", "radersi", "se raser", "면도하다"),
        t("to answer", "responder", "responder", "rispondere", "répondre", "대답하다"),
        t("to relieve", "aliviarse", "aliviar", "alleviare", "(se) soulager", "완화하다"),
        t("thin / skinny", "flaco", "magro", "magro", "maigre", "마른"),
        t("slender", "delgado", "esbelto", "snello", "mince", "날씬한"),
        t("during / for", "durante", "durante", "durante", "pendant", "동안"),
        t("healthy", "sano", "saudável", "sano", "sain", "건강한"),
        t("strict", "estricto / severo", "rigoroso", "severo", "sévère", "엄격한"),
        t("simple / uncomplicated", "simple", "simples", "semplice", "simple", "간단한"),
        t("to cough", "toser", "tossir", "tossire", "tousser", "기침하다"),
        t("to get sick", "enfermarse", "ficar doente", "ammalarsi", "tomber malade", "병에 걸리다"),
        t("doctor", "el médico", "o médico", "il medico", "le médecin", "의사"),
        t("pharmacy", "la farmacia", "a farmácia", "la farmacia", "la pharmacie", "약국"),
        t("prescription", "la receta", "a receita", "la ricetta", "l'ordonnance", "처방전"),
        t("fever", "la fiebre", "a febre", "la febbre", "la fièvre", "열"),
        t("cold (illness)", "el resfriado", "o resfriado", "il raffreddore", "le rhume", "감기"),
        t("pain", "el dolor", "a dor", "il dolore", "la douleur", "통증"),
        t("appointment", "la cita", "a consulta", "l'appuntamento", "le rendez-vous", "예약"),
        t("hospital", "el hospital", "o hospital", "l'ospedale", "l'hôpital", "병원"),
        t("nurse", "el enfermero / la enfermera", "o enfermeiro", "l'infermiere", "l'infirmier", "간호사"),
        t("pill", "la pastilla", "o comprimido", "la pastiglia", "le comprimé", "알약"),
        t("to take care", "cuidarse", "se cuidar", "curarsi", "se soigner", "몸 관리하다"),
        t("toothbrush", "el cepillo de dientes", "a escova de dentes", "lo spazzolino", "la brosse à dents", "칫솔"),
        t("toothpaste", "la pasta de dientes", "o creme dental", "il dentifricio", "le dentifrice", "치약"),
        t("soap", "el jabón", "o sabonete", "il sapone", "le savon", "비누"),
        t("mirror", "el espejo", "o espelho", "lo specchio", "le miroir", "거울"),
    ],
    "car": [
        t("accelerator", "el acelerador", "o acelerador", "l'acceleratore", "l'accélérateur", "액셀"),
        t("policeman", "el agente", "o policial", "l'agente", "l'agent", "경찰"),
        t("fender", "el guardabarros", "o para-lama", "il parafango", "l'aile", "펜더"),
        t("back / rear", "la parte trasera", "a traseira", "il retro", "l'arrière", "뒤"),
        t("front", "la parte delantera", "a dianteira", "l'anteriore", "l'avant", "앞"),
        t("battery", "la batería", "a bateria", "la batteria", "la batterie", "배터리"),
        t("button", "el botón", "o botão", "il pulsante", "le bouton", "버튼"),
        t("hood", "el capó", "o capô", "il cofano", "le capot", "보닛"),
        t("registration / title", "el permiso de circulación", "o documento do carro", "il libretto", "la carte grise", "차량 등록증"),
        t("road map", "el mapa de carreteras", "o mapa rodoviário", "la carta stradale", "la carte routière", "도로 지도"),
        t("seat belt", "el cinturón", "o cinto", "la cintura", "la ceinture", "안전벨트"),
        t("heating", "la calefacción", "o aquecimento", "il riscaldamento", "le chauffage", "히터"),
        t("traffic ticket", "la multa", "a multa", "la multa", "la contravention", "교통 벌금"),
        t("flat tire", "el pinchazo", "o pneu furado", "la gomma a terra", "la crevaison", "펑크"),
        t("starter", "el motor de arranque", "o motor de partida", "il motorino d'avviamento", "le démarreur", "시동 모터"),
        t("clutch", "el embrague", "a embreagem", "la frizione", "l'embrayage", "클러치"),
        t("windshield wiper", "el limpiaparabrisas", "o limpador", "il tergicristallo", "l'essuie-glace", "와이퍼"),
        t("to turn off", "apagar", "desligar", "spegnere", "éteindre", "끄다"),
        t("to fill the tank", "llenar el depósito", "encher o tanque", "fare il pieno", "faire le plein", "주유하다"),
        t("to brake", "frenar", "frear", "frenare", "freiner", "브레이크를 밟다"),
        t("to inflate", "hinchar", "encher", "gonfiare", "gonfler", "바람을 넣다"),
        t("to turn on (a light)", "encender", "acender", "accendere", "allumer", "켜다"),
        t("to stall / flip", "calarse / volcar", "capotear / morrer", "impennarsi / capottare", "capoter", "전복되다"),
        t("stoplight", "el semáforo", "o semáforo", "il semaforo", "le feu", "신호등"),
        t("brake", "el freno", "o freio", "il freno", "le frein", "브레이크"),
        t("turn signal", "el intermitente", "a seta", "la freccia", "l'indicateur", "방향지시등"),
        t("gauge", "el indicador", "o medidor", "l'indicatore", "la jauge", "계기판"),
        t("horn", "el claxon", "a buzina", "il clacson", "le klaxon", "경적"),
        t("flashlight", "la linterna", "a lanterna", "la torcia", "la lampe de poche", "손전등"),
        t("engine / motor", "el motor", "o motor", "il motore", "le moteur", "엔진"),
        t("breakdown", "la avería", "a pane", "il guasto", "la panne", "고장"),
        t("windshield", "el parabrisas", "o para-brisa", "il parabrezza", "le pare-brise", "앞유리"),
        t("headlight", "el faro", "o farol", "il faro", "le phare", "헤드라이트"),
        t("license plate", "la matrícula", "a placa", "la targa", "la plaque", "번호판"),
        t("registration plate", "la matrícula", "a placa", "la targa", "la plaque d'immatriculation", "등록 번호판"),
        t("tire", "el neumático", "o pneu", "lo pneumatico", "le pneu", "타이어"),
        t("wheel", "la rueda", "a roda", "la ruota", "la roue", "바퀴"),
        t("gas station", "la gasolinera", "o posto", "il distributore", "la station-service", "주유소"),
        t("pavement / sidewalk", "la acera", "a calçada", "il marciapiede", "le trottoir", "인도"),
        t("speed", "la velocidad", "a velocidade", "la velocità", "la vitesse", "속도"),
        t("steering wheel", "el volante", "o volante", "il volante", "le volant", "핸들"),
        t("to tow", "remolcar", "rebocar", "trainare", "remorquer", "견인하다"),
        t("to park", "aparcar", "estacionar", "parcheggiare", "stationner", "주차하다"),
        t("to fall", "caer", "cair", "cadere", "tomber", "떨어지다"),
        t("to guide", "guiar", "guiar", "guidare", "guider", "안내하다"),
        t("to hit / run into", "chocar", "bater", "urtare", "heurter", "부딪히다"),
        t("driver's license", "el carnet de conducir", "a carteira", "la patente", "le permis de conduire", "운전면허"),
        t("gasoline", "la gasolina", "a gasolina", "la benzina", "l'essence", "휘발유"),
        t("unleaded", "sin plomo", "sem chumbo / comum", "senza piombo", "sans plomb", "무연"),
        t("parking", "el aparcamiento", "o estacionamento", "il parcheggio", "le parking", "주차장"),
        t("highway", "la autopista", "a autoestrada", "l'autostrada", "l'autoroute", "고속도로"),
        t("insurance", "el seguro", "o seguro", "l'assicurazione", "l'assurance", "보험"),
        t("speed limit", "el límite de velocidad", "o limite de velocidade", "il limite di velocità", "la limitation de vitesse", "제한 속도"),
        t("traffic jam", "el atasco", "o congestionamento", "il traffico", "le bouchon", "교통 체증"),
        t("to start the car", "arrancar", "dar partida", "avviare", "démarrer", "시동을 걸다"),
        t("rearview mirror", "el retrovisor", "o retrovisor", "lo specchietto", "le rétroviseur", "백미러"),
        t("passenger", "el copiloto", "o passageiro", "il passeggero", "le passager", "동승자"),
        t("to buckle up", "abrocharse el cinturón", "pôr o cinto", "allacciare la cintura", "attacher sa ceinture", "벨트를 매다"),
        t("red light", "el semáforo en rojo", "o sinal vermelho", "il rosso", "le feu rouge", "빨간불"),
        t("to give way", "ceder el paso", "dar a preferência", "dare la precedenza", "céder le passage", "양보하다"),
        t("roundabout", "la rotonda", "a rotatória", "la rotonda", "le rond-point", "로터리"),
        t("toll", "el peaje", "o pedágio", "il pedaggio", "le péage", "통행료"),
        t("spare tire", "la rueda de recambio", "o estepe", "la ruota di scorta", "la roue de secours", "스페어 타이어"),
    ],
    "computers": [
        t("power supply", "la alimentación", "a fonte", "l'alimentazione", "l'alimentation", "전원"),
        t("tape", "la cinta", "a fita", "il nastro", "la bande", "테이프"),
        t("balance sheet / outcome", "el balance", "o balanço", "il bilancio", "le bilan", "결산"),
        t("punch card", "la tarjeta perforada", "o cartão perfurado", "la scheda perforata", "la carte perforée", "천공 카드"),
        t("cassette", "el casete", "a fita cassete", "la cassetta", "la cassette", "카세트"),
        t("circuit", "el circuito", "o circuito", "il circuito", "le circuit", "회로"),
        t("keyboard", "el teclado", "o teclado", "la tastiera", "le clavier", "키보드"),
        t("glue", "el pegamento", "a cola", "la colla", "la colle", "풀"),
        t("configuration", "la configuración", "a configuração", "la configurazione", "la configuration", "설정"),
        t("pencil", "el lápiz", "o lápis", "la matita", "le crayon", "연필"),
        t("criterion", "el criterio", "o critério", "il criterio", "le critère", "기준"),
        t("typist", "el dactilógrafo", "o datilógrafo", "il dattilografo", "le dactylo", "타자수"),
        t("industrial design", "el diseño industrial", "o desenho industrial", "il disegno industriale", "le dessin industriel", "산업 디자인"),
        t("screen", "la pantalla", "a tela", "lo schermo", "l'écran", "화면"),
        t("whole / set", "el conjunto", "o conjunto", "l'insieme", "l'ensemble", "전체"),
        t("input / entrance", "la entrada", "a entrada", "l'ingresso / l'input", "l'entrée", "입력"),
        t("scanner", "el escáner", "o scanner", "lo scanner", "l'explorateur / le scanner", "스캐너"),
        t("printer", "la impresora", "a impressora", "la stampante", "l'imprimante", "프린터"),
        t("computer science", "la informática", "a informática", "l'informatica", "l'informatique", "컴퓨터 과학"),
        t("engineer", "el ingeniero", "o engenheiro", "l'ingegnere", "l'ingénieur", "엔지니어"),
        t("software", "el software", "o software", "il software", "le logiciel", "소프트웨어"),
        t("typewriter", "la máquina de escribir", "a máquina de escrever", "la macchina da scrivere", "la machine à écrire", "타자기"),
        t("tape recorder", "el magnetófono", "o gravador", "il registratore", "le magnétophone", "녹음기"),
        t("hammer", "el martillo", "o martelo", "il martello", "le marteau", "망치"),
        t("hardware", "el hardware", "o hardware", "l'hardware", "le matériel", "하드웨어"),
        t("monthly (adj.)", "mensual", "mensal", "mensile", "mensuel", "월간의"),
        t("modem", "el módem", "o modem", "il modem", "le modem", "모뎀"),
        t("toll-free number", "el número gratuito", "o número 0800", "il numero verde", "le numéro vert", "수신자 부담 번호"),
        t("computer", "el ordenador", "o computador", "il computer", "l'ordinateur", "컴퓨터"),
        t("paper", "el papel", "o papel", "la carta", "le papier", "종이"),
        t("surge protector", "el protector de sobretensión", "o filtro de linha", "la protezione da sovratensione", "le parasurtenseur", "서지 보호기"),
        t("chip", "el chip", "o chip", "il chip", "la puce", "칩"),
        t("register / log", "el registro", "o registro", "il registro", "le registre", "기록"),
        t("ribbon", "la cinta", "a fita", "il nastro", "le ruban", "리본"),
        t("diagram / sketch", "el esquema", "o esquema", "lo schema", "le schéma", "도식"),
        t("output / exit", "la salida", "a saída", "l'uscita / l'output", "la sortie", "출력"),
        t("mouse", "el ratón", "o mouse", "il mouse", "la souris", "마우스"),
        t("pen", "el bolígrafo", "a caneta", "la penna", "le stylo", "펜"),
        t("light pen", "el lápiz óptico", "a caneta óptica", "la penna ottica", "le stylo lumineux", "라이트펜"),
        t("screwdriver", "el destornillador", "a chave de fenda", "il cacciavite", "le tournevis", "드라이버"),
        t("password", "la contraseña", "a senha", "la password", "le mot de passe", "비밀번호"),
        t("file", "el archivo", "o arquivo", "il file", "le fichier", "파일"),
        t("to download", "descargar", "baixar", "scaricare", "télécharger", "다운로드하다"),
        t("wifi", "el wifi", "o wi-fi", "il wifi", "le wifi", "와이파이"),
        t("email", "el correo", "o e-mail", "l'email", "le courriel", "이메일"),
        t("phone", "el teléfono", "o telefone", "il telefono", "le téléphone", "전화"),
        t("to click", "hacer clic", "clicar", "cliccare", "cliquer", "클릭하다"),
        t("to save", "guardar", "salvar", "salvare", "enregistrer", "저장하다"),
        t("to delete", "borrar", "apagar", "cancellare", "supprimer", "삭제하다"),
        t("website", "el sitio web", "o site", "il sito", "le site web", "웹사이트"),
        t("browser", "el navegador", "o navegador", "il browser", "le navigateur", "브라우저"),
        t("app", "la aplicación", "o aplicativo", "l'app", "l'appli", "앱"),
        t("to charge (battery)", "cargar", "carregar", "caricare", "charger", "충전하다"),
        t("USB stick", "la memoria USB", "o pen drive", "la chiavetta", "la clé USB", "USB"),
        t("headphones", "los auriculares", "o fone", "le cuffie", "le casque", "헤드폰"),
        t("laptop", "el portátil", "o notebook", "il portatile", "l'ordinateur portable", "노트북"),
        t("to restart", "reiniciar", "reiniciar", "riavviare", "redémarrer", "재시작하다"),
        t("bug / crash", "el fallo", "o bug", "il bug", "le bug", "오류"),
        t("to log in", "iniciar sesión", "entrar", "accedere", "se connecter", "로그인하다"),
        t("attachment", "el archivo adjunto", "o anexo", "l'allegato", "la pièce jointe", "첨부파일"),
        t("to print", "imprimir", "imprimir", "stampare", "imprimer", "인쇄하다"),
        t("screen brightness", "el brillo", "o brilho", "la luminosità", "la luminosité", "밝기"),
    ],
    "clothes": [
        t("shirt", "la camisa", "a camisa", "la camicia", "la chemise", "셔츠"),
        t("pants", "los pantalones", "a calça", "i pantaloni", "le pantalon", "바지"),
        t("shoes", "los zapatos", "os sapatos", "le scarpe", "les chaussures", "신발"),
        t("coat", "el abrigo", "o casaco", "il cappotto", "le manteau", "코트"),
        t("size", "la talla", "o tamanho", "la taglia", "la taille", "사이즈"),
        t("socks", "los calcetines", "as meias", "i calzini", "les chaussettes", "양말"),
        t("hat", "el sombrero", "o chapéu", "il cappello", "le chapeau", "모자"),
        t("skirt", "la falda", "a saia", "la gonna", "la jupe", "치마"),
        t("jacket", "la chaqueta", "a jaqueta", "la giacca", "la veste", "재킷"),
        t("to wear", "llevar", "usar", "indossare", "porter", "입다"),
        t("fitting room", "el probador", "o provador", "il camerino", "l'essayage", "탈의실"),
        t("sweater", "el jersey", "o suéter", "il maglione", "le pull", "스웨터"),
        t("tie", "la corbata", "a gravata", "la cravatta", "la cravate", "넥타이"),
        t("belt", "el cinturón", "o cinto", "la cintura", "la ceinture", "벨트"),
        t("underwear", "la ropa interior", "a roupa de baixo", "la biancheria", "les sous-vêtements", "속옷"),
        t("pajamas", "el pijama", "o pijama", "il pigiama", "le pyjama", "잠옷"),
        t("gloves", "los guantes", "as luvas", "i guanti", "les gants", "장갑"),
        t("scarf", "la bufanda", "o cachecol", "la sciarpa", "l'écharpe", "목도리"),
        t("boots", "las botas", "as botas", "gli stivali", "les bottes", "부츠"),
        t("sandals", "las sandalias", "as sandálias", "i sandali", "les sandales", "샌들"),
        t("button", "el botón", "o botão", "il bottone", "le bouton", "단추"),
        t("pocket", "el bolsillo", "o bolso", "la tasca", "la poche", "주머니"),
        t("zipper", "la cremallera", "o zíper", "la cerniera", "la fermeture éclair", "지퍼"),
        t("cotton", "el algodón", "o algodão", "il cotone", "le coton", "면"),
        t("wool", "la lana", "a lã", "la lana", "la laine", "모직"),
        t("leather", "el cuero", "o couro", "la pelle", "le cuir", "가죽"),
        t("silk", "la seda", "a seda", "la seta", "la soie", "비단"),
        t("tight", "estrecho / ajustado", "apertado", "stretto", "serré", "끼는"),
        t("loose", "holgado", "folgado", "largo", "ample", "헐렁한"),
        t("clean", "limpio", "limpo", "pulito", "propre", "깨끗한"),
        t("dirty", "sucio", "sujo", "sporco", "sale", "더러운"),
        t("to put on", "ponerse", "vestir / pôr", "mettere", "mettre", "입다"),
        t("to take off", "quitarse", "tirar", "togliersi", "enlever", "벗다"),
        t("to change (clothes)", "cambiarse", "trocar de roupa", "cambiarsi", "se changer", "갈아입다"),
        t("laundry", "la colada", "a lavanderia", "il bucato", "le linge", "빨래"),
        t("to iron", "planchar", "passar", "stirare", "repasser", "다리다"),
        t("hanger", "la percha", "o cabide", "la gruccia", "le cintre", "옷걸이"),
        t("fashion", "la moda", "a moda", "la moda", "la mode", "패션"),
        t("casual", "informal", "casual", "casual", "décontracté", "캐주얼"),
        t("elegant", "elegante", "elegante", "elegante", "élégant", "우아한"),
        t("jeans", "los vaqueros", "o jeans", "i jeans", "le jean", "청바지"),
        t("T-shirt", "la camiseta", "a camiseta", "la maglietta", "le t-shirt", "티셔츠"),
        t("shorts", "los pantalones cortos", "o short", "i pantaloncini", "le short", "반바지"),
        t("dress", "el vestido", "o vestido", "il vestito", "la robe", "원피스"),
        t("raincoat", "el impermeable", "a capa de chuva", "l'impermeabile", "l'imperméable", "우비"),
        t("swimsuit", "el bañador", "o maiô / sunga", "il costume", "le maillot", "수영복"),
        t("glasses", "las gafas", "os óculos", "gli occhiali", "les lunettes", "안경"),
        t("watch", "el reloj", "o relógio", "l'orologio", "la montre", "시계"),
        t("purse / bag", "el bolso", "a bolsa", "la borsa", "le sac à main", "핸드백"),
        t("backpack", "la mochila", "a mochila", "lo zaino", "le sac à dos", "백팩"),
        t("it fits", "queda bien", "serve / cai bem", "sta bene", "ça va bien", "잘 맞다"),
        t("too small", "demasiado pequeño", "pequeno demais", "troppo piccolo", "trop petit", "너무 작다"),
        t("too big", "demasiado grande", "grande demais", "troppo grande", "trop grand", "너무 크다"),
        t("pair", "el par", "o par", "il paio", "la paire", "켤레"),
        t("laces", "los cordones", "os cadarços", "i lacci", "les lacets", "신발끈"),
        t("heels", "los tacones", "o salto", "i tacchi", "les talons", "힐"),
        t("cap", "la gorra", "o boné", "il cappellino", "la casquette", "모자 (캡)"),
        t("hoodie", "la sudadera con capucha", "o moletom", "la felpa", "le sweat à capuche", "후드티"),
        t("to match", "hacer juego", "combinar", "abbinare", "aller avec", "어울리다"),
        t("new", "nuevo", "novo", "nuovo", "neuf", "새"),
        t("second-hand", "de segunda mano", "de segunda mão", "di seconda mano", "d'occasion", "중고"),
        t("to try on", "probarse", "provar", "provare", "essayer", "입어 보다"),
    ],
    "weather": [
        t("weather", "el tiempo", "o tempo", "il tempo", "le temps", "날씨"),
        t("rain", "la lluvia", "a chuva", "la pioggia", "la pluie", "비"),
        t("sun", "el sol", "o sol", "il sole", "le soleil", "해"),
        t("cloud", "la nube", "a nuvem", "la nuvola", "le nuage", "구름"),
        t("wind", "el viento", "o vento", "il vento", "le vent", "바람"),
        t("today", "hoy", "hoje", "oggi", "aujourd'hui", "오늘"),
        t("tomorrow", "mañana", "amanhã", "domani", "demain", "내일"),
        t("now", "ahora", "agora", "adesso", "maintenant", "지금"),
        t("already", "ya", "já", "già", "déjà", "이미"),
        t("since", "desde", "desde", "da", "depuis", "부터"),
        t("umbrella", "el paraguas", "o guarda-chuva", "l'ombrello", "le parapluie", "우산"),
        t("of course", "por supuesto", "é claro", "certo", "bien sûr", "물론"),
        t("excellent", "excelente", "excelente", "eccellente", "excellent", "훌륭한"),
        t("yesterday", "ayer", "ontem", "ieri", "hier", "어제"),
        t("week", "la semana", "a semana", "la settimana", "la semaine", "주"),
        t("month", "el mes", "o mês", "il mese", "le mois", "달"),
        t("year", "el año", "o ano", "l'anno", "l'année", "해"),
        t("morning", "la mañana", "a manhã", "la mattina", "le matin", "아침"),
        t("noon", "el mediodía", "o meio-dia", "mezzogiorno", "midi", "정오"),
        t("evening", "la tarde / noche", "a noite", "la sera", "le soir", "저녁"),
        t("night", "la noche", "a noite", "la notte", "la nuit", "밤"),
        t("hour", "la hora", "a hora", "l'ora", "l'heure", "시간"),
        t("minute", "el minuto", "o minuto", "il minuto", "la minute", "분"),
        t("spring", "la primavera", "a primavera", "la primavera", "le printemps", "봄"),
        t("summer", "el verano", "o verão", "l'estate", "l'été", "여름"),
        t("autumn", "el otoño", "o outono", "l'autunno", "l'automne", "가을"),
        t("winter", "el invierno", "o inverno", "l'inverno", "l'hiver", "겨울"),
        t("fog", "la niebla", "o nevoeiro", "la nebbia", "le brouillard", "안개"),
        t("storm", "la tormenta", "a tempestade", "il temporale", "l'orage", "폭풍"),
        t("lightning", "el relámpago", "o relâmpago", "il lampo", "l'éclair", "번개"),
        t("thunder", "el trueno", "o trovão", "il tuono", "le tonnerre", "천둥"),
        t("snow", "la nieve", "a neve", "la neve", "la neige", "눈"),
        t("ice", "el hielo", "o gelo", "il ghiaccio", "la glace", "얼음"),
        t("rainbow", "el arcoíris", "o arco-íris", "l'arcobaleno", "l'arc-en-ciel", "무지개"),
        t("temperature", "la temperatura", "a temperatura", "la temperatura", "la température", "기온"),
        t("degrees", "los grados", "os graus", "i gradi", "les degrés", "도"),
        t("forecast", "el pronóstico", "a previsão", "le previsioni", "la météo", "일기예보"),
        t("cloudy", "nublado", "nublado", "nuvoloso", "nuageux", "흐린"),
        t("sunny", "soleado", "ensolarado", "soleggiato", "ensoleillé", "맑은"),
        t("rainy", "lluvioso", "chuvoso", "piovoso", "pluvieux", "비 오는"),
        t("snowy", "con nieve", "com neve", "nevoso", "neigeux", "눈 오는"),
        t("humid", "húmedo", "úmido", "umido", "humide", "습한"),
        t("dry", "seco", "seco", "secco", "sec", "건조한"),
        t("hot", "calor / caliente", "quente", "caldo", "chaud", "더운"),
        t("cold", "frío", "frio", "freddo", "froid", "추운"),
        t("chilly", "fresco", "fresco", "fresco", "frais", "쌀쌀한"),
        t("to rain", "llover", "chover", "piovere", "pleuvoir", "비가 오다"),
        t("to snow", "nevar", "nevar", "nevicare", "neiger", "눈이 오다"),
        t("to shine", "brillar", "brilhar", "splendere", "briller", "빛나다"),
        t("early", "temprano", "cedo", "presto", "tôt", "일찍"),
        t("late", "tarde", "tarde", "tardi", "tard", "늦게"),
        t("always", "siempre", "sempre", "sempre", "toujours", "항상"),
        t("never", "nunca", "nunca", "mai", "jamais", "절대"),
        t("often", "a menudo", "muitas vezes", "spesso", "souvent", "자주"),
        t("sometimes", "a veces", "às vezes", "qualche volta", "quelquefois", "가끔"),
        t("maybe", "quizá", "talvez", "forse", "peut-être", "아마"),
        t("what time is it?", "¿qué hora es?", "que horas são?", "che ore sono?", "quelle heure est-il ?", "몇 시예요?"),
        t("it's pouring", "llueve a cántaros", "está caindo um dilúvio", "piove a dirotto", "il pleut des cordes", "비가 억수같이"),
        t("it's windy", "hace viento", "está ventando", "tira vento", "il y a du vent", "바람이 분다"),
        t("it's nice out", "hace buen tiempo", "está um tempo bom", "è bel tempo", "il fait beau", "날씨가 좋다"),
        t("it's bad out", "hace mal tiempo", "está um tempo ruim", "è brutto tempo", "il fait mauvais", "날씨가 나쁘다"),
        t("season", "la estación", "a estação", "la stagione", "la saison", "계절"),
        t("weekend", "el fin de semana", "o fim de semana", "il weekend", "le week-end", "주말"),
        t("day", "el día", "o dia", "il giorno", "le jour", "날"),
        t("date", "la fecha", "a data", "la data", "la date", "날짜"),
        t("calendar", "el calendario", "o calendário", "il calendario", "le calendrier", "달력"),
        t("to get dark", "anochecer", "anoitecer", "imbrunire", "faire nuit", "어두워지다"),
        t("sunrise", "el amanecer", "o nascer do sol", "l'alba", "le lever du soleil", "일출"),
        t("sunset", "la puesta de sol", "o pôr do sol", "il tramonto", "le coucher du soleil", "일몰"),
        t("coat (for rain/cold)", "el abrigo", "o casaco", "il cappotto", "le manteau", "코트"),
    ],
}

